@startuml
set separator none

skinparam {
  shadowing false
  arrowFontSize 15
  defaultTextAlignment center
  wrapWidth 100
  maxMessageSize 100
}
hide stereotype

skinparam rectangle<<_transparent>> {
  BorderColor transparent
  BackgroundColor transparent
  FontColor transparent
}

skinparam rectangle<<1>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
}
rectangle "==Component" <<1>>


@enduml